// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:022fcc51-ba36-4981-88da-1dd42321d7c0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_wkUoYZ2Hd",
    "aws_user_pools_web_client_id": "7ag192mjkrmp7dibkfs7r15n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://s6pix2l45rb4dbouomn5kao4ie.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-sey6nzz2rbgu7jgzm3xw7hhzee"
};


export default awsmobile;
