// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:022fcc51-ba36-4981-88da-1dd42321d7c0",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_wkUoYZ2Hd",
    "aws_user_pools_web_client_id": "7ag192mjkrmp7dibkfs7r15n",
    "oauth": {}
};


export default awsmobile;
